### ISSUE TITLE
Overview swipe stops working after a while

### ISSUE THREAD

**Issue by vvitez** [JoseExposito/gnome-shell-extension-x11gestures#11]
### Describe the bug

After some while, the three finger swipe up still does the transision animation, but the instant the fingers leave the touchpad, it jumps right back into the workspace you tried to get out of.

### Expected behaviour

Go into overview mode.

### Actual behaviour

Bugs back into the current workspace.
Note that sometimes, if the three finger swipe up is very very short, then it still works somehow.

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

I left touchegg the exact same way it was after installing, no custom configs. 

### Your environment

 * Extension version: newest
 * Touchégg version: newest
 * Operating System: Arch Linux
 * GNOME Shell Version: newest

Hey, I'll try to look into the code and see if there is a quick fix. Awesome work you did mate!

**Comment by JoseExposito** [comment]
Hi! Could you add your exact GNOME Shell version, please?

Some changes were introduced in 40.1 and I had to adjust this values:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/src/v40/SwipeTracker40.js#L36

It might not being working fine in your version... you can try to adjust them to see if it is easier to perform the gestures that way.

**Comment by vvitez** [comment]
Hi :)
I'm on Gnome 40.1

So the thing is, most of the time it works fine. After a while, though, and I haven't yet found the exact conditions under which it breaks, it still moves normally and everything, but as soon as I let go with my fingers, it just jumps back into the workspace. So far it has only happened when an application was in full screen mode and a quick fix is just to reload the gnome shell with alt-F2 r.  I'll try to trigger this bug in a reproducable way and update you if I know the conditions needed.
Have a good one :)

**Comment by JoseExposito** [comment]
Hi! Thanks a lot for taking the time to debug the issue.

I could be wrong, but my intuition is that this is a GNOME Shell bug. Do you have any [Touchégg](https://github.com/JoseExposito/touchegg) action configured? You can easily check it from the [GUI](https://github.com/JoseExposito/touche). If so, do they also stop working?

Quick overview so it is easier to understand why I think it is a GNOME Shell bug:

- Touchégg runs in two parts: A daemon that gathers the gestures and a client that perform actions in your desktop
- This extension is just another client that is integrated into GNOME Shell

You mentioned that switching between workspaces works. That means that the daemon and the extension are still working, but, for some reason, you are not able to perform the open activities/app grid gestures... It looks like the issue is somewhere else.

Anyway, I'm finishing a development in Mutter/GTK and I don't want to mess up with my Fedora installation, but as soon as I finish that I'll see if I can update/compile GNOME Shell 40.1 and see if the issue is also present in Wayland.

**Comment by vvitez** [comment]
So I don't have any Touchégg action configured.  It might be a gnome shell bug, but what confuses me is the following behaviour.
For example, right now it is in the buggy state. I can do a long swipe up and it looks normal and I see th activities overview as long as I have my fingers on the touchpad. If I let go now, it just goes back into the current workspace. But if I do a very very short and fast swipe and let go with my fingers during the swipe then it just goes into normal overview and stays there. So under that condition it always works, just if i do it in a normal speed it doesn't work. I'll do a Screen Recording with first a normal, then a slow and then the very very quick and short swipe(my gnome dock is disabled but the same bug happens without the extension that disables it).

https://user-images.githubusercontent.com/66899393/117976825-7ce33800-b330-11eb-87ad-65c472bcccc9.mp4


).

**Comment by JoseExposito** [comment]
Yes, definitely a GNOME Shell bug, the extension is working and trying to open the activities view, but the change is not being picked up. I'll try to reproduce it in Wayland  to report it :smile:
