### ISSUE TITLE
Option for not loading on Wayland

### ISSUE THREAD

**Issue by hyphone** [JoseExposito/gnome-shell-extension-x11gestures#13]
Hello and thank you for your great work and engagement!

Currently I'm often switching between Wayland and X11 because I have an Optimus dual GPU laptop and depending on what mode I am GDM loads the X11 or Wayland session (because NVIDIA is not supported).

I would like to see a feature that the extension does not try to establish a connection to touchegg on a Wayland session.

What do you think?

**Comment by JoseExposito** [comment]
Hi!

In theory, I'm checking if the current session is the Wayland session and exit silently (well, I print a log https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/master/extension.js#L32).

Is it showing an error in your case?

**Comment by hyphone** [comment]
Thank you for your quick reply.

Right... I was irritated by the regular Touchegg process in combination with wayland:

```
Jun 01 19:19:30 computername touchegg.desktop[2844]: Error connecting to Touchégg daemon: Could not connect: Connection refused
Jun 01 19:19:30 computername touchegg.desktop[2844]: Reconnecting in 5 seconds...
```

**Comment by hyphone** [comment]
I'm wondering why there is the autostart in `/etc/xdg/autostart/touchegg.desktop` when there is a systemd service.

**Comment by JoseExposito** [comment]
Aham, ok, that's a different issue.

It's not related to the extension but with Touchégg it self. It's weird that it is not able to connect to the daemon though, it shouldn't fail...

Could you attach the logs of the daemon in the Wayland session, please?

In a terminal:
```
$ sudo journalctl -u touchegg -b -f
```
(Control + C to exit)


> I'm wondering why there is the autostart in /etc/xdg/autostart/touchegg.desktop when there is a systemd service.

The reason is that Touchégg runs in 2 different processes:

 - A daemon, started by systemd as part of the `input` group. It gathers the gestures and sends them to clients
 - A client, started by the desktop file you mentioned. It executes generic [actions and animations](https://github.com/JoseExposito/touchegg#available-actions)

This extension is just another client integrated with GNOME Shell.

**Comment by hyphone** [comment]
Thank you very much for the explaination.
I deactivated the service and this is then understandable because the service is not meant to get disabled but when it fails it should restart itself.

Will touchegg interfer with Wayland or XWayland when I keep it enabled? I would like to only use it while on X11.

**Comment by JoseExposito** [comment]
It could interfere with XWayland applications, almost every action works with XWayland apps. Other that that, it shouldn't cause any trouble.
