### ISSUE TITLE
please add gesture multiplier to the preferences 

### ISSUE THREAD

**Issue by vvitez** [JoseExposito/gnome-shell-extension-x11gestures#16]
Since you reverted the change to have different multipliers for gnome 40.1 and above vs gnome 40, it would be very nice to be able to change the current multiplier of 3.5 in the preferences. Right now, I have to basically use the entire touchpad and do quick, long swipes, for any of the gestures to work. 

Thanks to your good documentation i can just clone it and change the value myself, but having it as a setting would be nice to have.

Anyways, have an awesome day! :D

**Comment by JoseExposito** [comment]
Hi!

Make sure to install the latest version of Touchégg so gestures are back to normal:
https://github.com/JoseExposito/touchegg/releases/tag/2.0.10

There was a change in libinput 1.18 that changed the amount of movement required to perform a gesture.

After updating, you should be able to perform a quick and short swipe to switch desktops or open the activities view, just like before.

About adding an option... I'm not a big fan of providing such an option, mainly because it hides bugs. Here are the reasons:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/15#issuecomment-857908645

**Comment by vvitez** [comment]
Oh, I see, thanks a lot!
