### ISSUE TITLE
fedora 34 gnome 40.beta.0 incompatible

### ISSUE THREAD

**Issue by sleepforlife** [JoseExposito/gnome-shell-extension-x11gestures#3]
I cannot install the extensions I get an error like ;;;;

![Ekran Görüntüsü - 2021-03-14 19-24-49](https://user-images.githubusercontent.com/50239677/111076065-d5968000-84fb-11eb-89d0-cfc8c5726d11.png)

I tried to install it manually. gnome does not see the extensions

**Comment by sleepforlife** [comment]
$ gnome-shell --version
GNOME Shell 40.rc

**Comment by JoseExposito** [comment]
Hi @sleepforlife 

Thanks for the heads up. I just updated the GNOME Shell compatible version to include 40 and 40.rc. Not the "INCOMPATIBLE" tag is not displayed anymore, but in my case the installation process fails (without showing any error), so, I'm not sure what's going on.

Let's hope that it gets fixed by the release of GNOME 40, I'll keep an eye on it.

**Comment by sleepforlife** [comment]
thank you very much . it works
