### ISSUE TITLE
Gestures require a lot more push with Ubuntu 22.04/GNOME 42

### ISSUE THREAD

**Issue by bluesabre** [JoseExposito/gnome-shell-extension-x11gestures#38]
### Describe the bug

I've noticed that the gestures are a lot harder to activate with Ubuntu 22.04. Previously, a small push would be all that was needed to switch workspaces or show the activity view. Now it requires either a really big swipe or a fast one to switch workspaces and I frequently have to try multiple times to get the activities view to show. Otherwise, I just see the bump effect.

### Expected behaviour

Gestures should be 1:1 like in Wayland, or at least activate with less movement.

### Actual behaviour

Gestures are difficult to activate.

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Extension version: 14
 * Touchégg version: 2.0.14
 * Operating System: Ubuntu 22.04
 * GNOME Shell Version: 42.1
 * Are you using other GNOME Shell extensions?
    * List the other extensions: Desktop Icons NG (DING), Ubuntu Appindicators, Ubuntu Dock
    * Can you reproduce the issue after disabling the other extensions? Yes, issue continues after disabling the other extensions

**Comment by JoseExposito** [comment]
Hi Sean,

Thanks for the bug report.

This is usually caused by a mismatch between the libinput present in your system and the version Touchégg was compile against:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/14

What is your libinput version? And how did you install Touchégg?

The PPA package should have been compiled against the correct version of libinput, in case you installed it using a different method.

**Comment by bluesabre** [comment]
Ah, perfect. Yes, I had installed with the release .deb instead of the PPA. Using the PPA version instead resolves the issue.

Sorry for the noise and thanks for the prompt response!
