### ISSUE TITLE
Detecting touchegg-git

### ISSUE THREAD

**Issue by not-a-dev-stein** [JoseExposito/gnome-shell-extension-x11gestures#5]
Currently there´s an issue installing touchegg from the AUR in Arch, while touchegg-git installs and works perfectly fine, but with the git version the extension always prompts me to install touchegg at boot.

Is there a way for it to detect that the git version is installed? It isn´t even a **_real™_** issue, but more of an annoyance.

**Comment by JoseExposito** [comment]
Hi!

Could you check that the file `/usr/share/touchegg/touchegg.conf` is present in your system, please?

The notification should be sent if that file is not present, because that's the way the extension uses checks if Touchégg is installed or not.

**Comment by JoseExposito** [comment]
By the way, are you on vanilla Arch? This issue is similar to https://github.com/JoseExposito/touchegg/issues/481 but that user was on Artix.

**Comment by not-a-dev-stein** [comment]
> Could you check that the file `/usr/share/touchegg/touchegg.conf` is present in your system, please?

Weirdly enough, there isn´t one. But both touchegg and the extension work perfectly without one.

> By the way, are you on vanilla Arch? This issue is similar to [JoseExposito/touchegg#481](https://github.com/JoseExposito/touchegg/issues/481) but that user was on Artix.

No, the package is failing sha512sums validity verification. I think it´s going to be fixed soon, but until then I´m using the git version.

**Comment by JoseExposito** [comment]
Cool, the git version doesn't seem to install every required piece. It works because you have a config in your home (`~/.config/touchegg/touchegg.conf`) and that one is used.

Just copy the config file from `~/.config/touchegg/touchegg.conf` to `/usr/share/touchegg/touchegg.conf`.

This should also fix problems with [Touché](https://github.com/JoseExposito/touche) if you are using it.
