### ISSUE TITLE
Add GNOME 45 compatibility

### ISSUE THREAD

**Issue by NetradeepakC** [JoseExposito/gnome-shell-extension-x11gestures#51]
Please add Gnome 45 support to this extension.

Currently GNOME 44 is the latest shell supported

**Comment by JoseExposito** [comment]
Hi!

GNOME 45 is already supported in the latest release:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/18

However, it is not available in the GNOME Shell Extension web page because it is under review.
I can't give you an ETA for the review process, but for the moment you can install the extension from the zip file available in the releas page.
