### ISSUE TITLE
Gnome extensions indicate that X11 Gestures are outdated.

### ISSUE THREAD

**Issue by guilhermesrc** [JoseExposito/gnome-shell-extension-x11gestures#52]
### Describe the bug

The Gnome Extensions website does not allow downloading of the extension in Gnome 45.

### Your environment
Arch Linux
Gnome 45

**Comment by JoseExposito** [comment]
Hi!

GNOME 45 is already supported in the latest release:
https://github.com/JoseExposito/gnome-shell-extension-x11gestures/releases/tag/18

However, it is not available in the GNOME Shell Extension web page because it is under review.
I can't give you an ETA for the review process, but for the moment you can install the extension from the zip file available in the release page.

Duplicated of https://github.com/JoseExposito/gnome-shell-extension-x11gestures/issues/51

Leaving this one open so it is easier to find.

**Comment by DarkXero-dev** [comment]
Installing from zip doesn't solve the issue coz extensions app will automatically update it next logon or reboot. But thanks

**Comment by AaronSwearingen** [comment]
You can stop the automatic downgrade by changing the name of the extension folder and the uuid in metadata.json. That'll break the auto update, so you'll want to undo it when the new version is finally published.

Speaking of which, I'm subbed to this issue and it would be great if it gets closed when the new ver is published as a notification of sorts.

**Comment by guilhermesrc** [comment]
It's available now! Thanks!
