### ISSUE TITLE
4 finger gestures on gnome 40

### ISSUE THREAD

**Issue by S41d** [JoseExposito/gnome-shell-extension-x11gestures#6]
### Is your feature request related to a problem? Please describe

4 finger gestures are replaced with 3 finger ones on Gnome 40, i find 4 finger gestures a lot more comfortable to use than 3 finger ones.

### Describe the solution you'd like

Adding the ability to choose between 3 finger and 4 finger gestures, or 4 finger gestures doing the same as 3 finger ones.

**Comment by JoseExposito** [comment]
Hi, the intention of this feature is to mimic that GNOME is doing, but this could be an interesting addition, I'm going to mark it as enhancement... Let's see if someone open a PR :smile:

**Comment by filariow** [comment]
@S41d as a temporary solution I disabled the extension and edited the file [src/v40/EntryPoint40.js](https://github.com/JoseExposito/gnome-shell-extension-x11gestures/blob/28f503dfc6f0e519e858918baa1c1f7c98782005/src/v40/EntryPoint40.js) in my local installation replacing all the `3` (L 49, 78, 106).

Finally, I made a backup and removed the local touchegg config file, restarted the touchegg service (to recreate a clean config file) and enabled again the extension.

```bash
mv ~/.config/touchegg/touchegg.conf{,.bkp}  # backup the touchegg.config file
sudo systemctl restart touchegg.service
```

I had to delete the touchegg.config file because touché was still showing the 3 fingers shortcut as `Used by Gnome Shell`.

**Comment by KristianUSN** [comment]
If this change is possible, would it also be possible to add compatibility with this extension?
https://extensions.gnome.org/extension/4245/gesture-improvements/

**Comment by JoseExposito** [comment]
I don't know if both extensions will work together, it depends on how it's implemented. However, adding compatibility is not something I can ensure, it'll probably break between releases, so not really something I can work on.

However, if you want extra gestures, you can already use all of this out of the box:
https://github.com/JoseExposito/touchegg#readme

Even with a GUI to configure them:
https://github.com/JoseExposito/touche

By the way, closing this issue, as the branch is already merged :+1:
